# Q-Learning Temporal Difference

In [12]:
import numpy as np
import random
import time


In [13]:
import gymnasium as gym
from IPython.display import clear_output

# Create FrozenLake
env = gym.make("FrozenLake-v1", is_slippery=False, render_mode="ansi", map_name="4x4")

In [14]:
# Hyperparameters:

N_STATES = 16   # the length of the 4 dimensional world
ACTIONS = ['left', 'down', 'right', 'up']     # available actions
# 0: Move left
# 1: Move down
# 2: Move right
# 3: Move up

EPSILON = 0.9   # greedy policy
ALPHA = 0.1     # learning rate
GAMMA = 0.9    # discount factor
THETA = 1e-8            # Convergence threshold


FRESH_TIME = 0.3    # refresh/pause time for one move used in time.sleep

MAX_EPISODES = 50   # maximum episodes

num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
epsilon = 0.2

In [15]:
# Create an initial Q table 
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
# This is our Policy (AKA Model) (AKA Q Table)
def choose_action(env, state, q_table):

    # Exploration-exploitation trade-off
    exploration_rate_threshold = random.uniform(0, 1)
    if exploration_rate_threshold > epsilon:
        action = np.argmax(q_table[state,:])
    else:
        action = env.action_space.sample()


    return action

In [17]:
def q_learning_TD(env, q_table):
    for episode in range(num_episodes):
        # Fix reset() usage
        state, info = env.reset()
       
        for step in range(max_steps_per_episode):
  
            action = choose_action(env, state, q_table)

            new_state, reward, terminated, truncated, info = env.step(action)
            
            # Update Q-table for Q(s,a)
            q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                                    learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

            state = new_state

            
            # #Print info
            # print(f"Episode Step {step} Given Action {action} I got reward {reward} and next state {new_state}")
            

            # the goal position in the 4x4 map can be calculated as follows: 3 * 4 + 3 = 15.
            if reward and new_state==15:
                print("You Won!!!")
                print(f"Episode {episode + 1} ended with reward: {reward}")
                env.close()
                break
            
            #Check for Termination
            if terminated or truncated:
                print("GAME OVER --- Terminated!!!")
                print(f"Episode {episode + 1} ended with reward: {reward}")
                env.close()
                break

    
    return q_table

In [18]:
q_table = q_learning_TD(env, q_table)

GAME OVER --- Terminated!!!
Episode 1 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 2 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 3 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 4 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 5 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 6 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 7 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 8 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 9 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 10 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 11 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 12 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 13 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 14 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 15 ended with reward: 0.0
GAME OVER --- Terminated!!!
Episode 16 ended with reward: 0.0
GAME OVER --- Ter

In [19]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)




********Q-table********

[[0.94148015 0.95099005 0.93206535 0.94148015]
 [0.94148015 0.         0.82217976 0.71872117]
 [0.92628449 0.18772866 0.0118784  0.21904698]
 [0.16967336 0.         0.         0.        ]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.77497696]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.95024467 0.99       0.         0.46367002]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]


In [20]:
def testModel(env, q_table):
    #Deploy Code
    actionLog = []
    for episode in range(1):
        state, info = env.reset()  # Fix: Unpack both state and info
        done = False
        print("*****EPISODE ", episode+1, "*****\n\n\n\n")
        time.sleep(1)

        for step in range(max_steps_per_episode):
            clear_output(wait=True)
            env.render()
            time.sleep(0.3)

            action = np.argmax(q_table[state,:])
            actionLog.append(action)
            # Fix: Handle all five return values from step()
            new_state, reward, terminated, truncated, info = env.step(action)
            done = terminated or truncated  # Combine both terminal conditions

            if done:
                clear_output(wait=True)
                env.render()
                if reward == 1:
                    print("****You reached the goal!****")
                    time.sleep(3)
                else:
                    print("****You fell through a hole!****")
                    time.sleep(3)
                clear_output(wait=True)
                break

            state = new_state

    env.close()
    
    return actionLog


In [21]:
# Create FrozenLake
env = gym.make("FrozenLake-v1", is_slippery=False, render_mode="human", map_name="4x4")

actionLog = testModel(env, q_table)


****You reached the goal!****


In [22]:
len(actionLog)

6