In [59]:
import numpy as np
import random
import time
from IPython.display import clear_output

np.random.seed(2)  # reproducible

In [60]:
N_STATES = 4*4   # the size of the grid

ACTIONS = ['left', 'down', 'right','up']     # available actions

# 0: Move left
# 1: Move down
# 2: Move right
# 3: Move up


EPSILON = 0.9   # greedy policy
ALPHA = 0.1     # learning rate
GAMMA = 0.9    # discount factor

MAX_EPISODES = 13   # maximum episodes

FRESH_TIME = 0.3    # refresh/pause time for one move used in time.sleep

In [61]:
def build_q_table(n_states, actions):
    table = pd.DataFrame(
        np.zeros((n_states, len(actions))),     # q_table initial values
        columns=actions,    # actions's name
    )
    #print(table)    # show table
    return table

In [62]:
def choose_action(state, q_table):
    # This is how to choose an action
    state_actions = q_table.iloc[state, :]

    if (np.random.uniform() > EPSILON) or ((state_actions == 0).all()):  # act non-greedy or state-action have no value
        action_name = np.random.choice(ACTIONS)
    else:   # act greedy
        action_name = state_actions.idxmax()    # replace argmax to idxmax as argmax means a different function in newer version of pandas

    return action_name

In [63]:
#Exploitation Method
def actionWithTrainedModel(state,q_table):
  state_actions = q_table.iloc[state, :]
  action_name = state_actions.idxmax()
  return action_name

In [64]:
# def get_env_feedback(S, A):
#     # This is how agent will interact with the environment
#     if A == 'right':    # move right
#         if S == N_STATES - 2:   # terminate
#             S_ = 'terminal'
#             R = 1
#         else:
#             S_ = S + 1
#             R = 0
#     else:   # move left
#         R = 0
#         if S == 0:
#             S_ = S  # reach the wall
#         else:
#             S_ = S - 1
#     return S_, R


In [65]:
# def update_env(S, episode, step_counter):
#     # This is how environment be updated
#     env_list = ['-']*(N_STATES-1) + ['T']   # '---------T' our environment
#     if S == 'terminal':
#         interaction = 'Episode %s: total_steps = %s' % (episode+1, step_counter)
#         print('\r{}'.format(interaction), end='')
#         time.sleep(2)
#         print('\r                                ', end='')
#     else:
#         env_list[S] = 'o'
#         interaction = ''.join(env_list)
#         print('\r{}'.format(interaction), end='')
#         time.sleep(FRESH_TIME)

In [66]:
import gymnasium as gym
from IPython.display import clear_output

# Create FrozenLake with human rendering (non-slippery)
env = gym.make("FrozenLake-v1", is_slippery=False, render_mode="human")

In [67]:
# q_table = build_q_table(N_STATES, ACTIONS)
# print(q_table)

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [68]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

epsilon = 0.2


In [69]:
# def rl(env):
#     # main part of RL loop
#     q_table = build_q_table(N_STATES, ACTIONS)
#     print(q_table)

#     for episode in range(MAX_EPISODES):
#         step_counter = 0
#         # S = 0
#         S, _ = env.reset()
#         print(f"\nEpisode {episode + 1} started")
        
#         terminated = False
#         # update_env(S, episode, step_counter)
#         while not terminated:
#         # for step in range(max_steps):

#             A = choose_action(S, q_table)
#             # A = env.action_space.sample()  # Random action
            
#             # S_, R = get_env_feedback(S, A)  # take action & get next state and reward
     
#             S_, R, terminated, truncated, _ = env.step(A)            
                
            
#             q_predict = q_table.loc[S, A]
#             # if S_ != 'terminal':
#             if S_ == 15:
#                 q_target = R     # next state is terminal
#                 terminated = True    # terminate this episode
               
#             else:
#                 q_target = R + GAMMA * q_table.iloc[S_, :].max()   # next state is not terminal

#             q_table.loc[S, A] += ALPHA * (q_target - q_predict)  # update
#             S = S_  # move to next state

#             # update_env(S, episode, step_counter+1)
#             step_counter += 1
#     return q_table

In [ ]:
# for episode in range(MAX_EPISODES):
#     step_counter = 0
#     # S = 0
#     S, _ = env.reset()
#     print(f"\nEpisode {episode + 1} started")
    
#     terminated = False
#     # update_env(S, episode, step_counter)
#     while not terminated:
#     # for step in range(max_steps):

#         A = choose_action(S, q_table)
#         # A = env.action_space.sample()  # Random action
        
#         # S_, R = get_env_feedback(S, A)  # take action & get next state and reward
    
#         S_, R, terminated, truncated, _ = env.step(A)            
            
        
#         q_predict = q_table.loc[S, A]
#         # if S_ != 'terminal':
#         if S_ == 15:
#             q_target = R     # next state is terminal
#             terminated = True    # terminate this episode
            
#         else:
#             q_target = R + GAMMA * q_table.iloc[S_, :].max()   # next state is not terminal

#         q_table.loc[S, A] += ALPHA * (q_target - q_predict)  # update
#         S = S_  # move to next state

#         # update_env(S, episode, step_counter+1)
#         step_counter += 1
# return q_table


for episode in range(num_episodes):
    state = env.reset()
    done = False

    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > epsilon:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)


        time.sleep(0.3)  # Slow down for better visualization

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] *  (1 - learning_rate)  + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))


        state = new_state

        if done == True:
            break



# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

ValueError: too many values to unpack (expected 4)

: 

In [ ]:
def rlDeploy(q_table):
    #Deploy Code
    actionLog = []
    for episode in range(1):
        state = env.reset()
        done = False
        print("*****EPISODE ", episode+1, "*****\n\n\n\n")
        time.sleep(1)

        for step in range(max_steps_per_episode):
            clear_output(wait=True)
            env.render()
            time.sleep(0.3)

            action = np.argmax(q_table[state,:])
            actionLog.append(action)
            new_state, reward, done, info = env.step(action)


            if done:
                clear_output(wait=True)
                env.render()
                if reward == 1:
                    print("****You reached the goal!****")
                    time.sleep(3)
                else:
                    print("****You fell through a hole!****")
                    time.sleep(3)
                clear_output(wait=True)
                break

            state = new_state

    env.close()


In [ ]:
rlDeploy(q_table)

InvalidIndexError: ((0, {'prob': 1}), slice(None, None, None))